const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('mateclawDesktop', {
  isDesktop: true,
  isPackaged: !process.env.MATECLAW_RENDERER_URL,
  electronVersion: process.versions.electron,
  getRuntimeInfo: () => ipcRenderer.invoke('mateclaw-desktop:get-runtime-info'),
  getServerConfig: () => ipcRenderer.invoke('mateclaw-desktop:get-server-config'),
  saveServerConfig: (config) => ipcRenderer.invoke('mateclaw-desktop:save-server-config', config),
  testServer: (config) => ipcRenderer.invoke('mateclaw-desktop:test-server', config),
  selectDirectory: () => ipcRenderer.invoke('mateclaw-desktop:select-directory'),
  selectFiles: (options) => ipcRenderer.invoke('mateclaw-desktop:select-files', options),
  readTextFile: (filePath) => ipcRenderer.invoke('mateclaw-desktop:read-text-file', filePath),
  workspaceTree: (options) => ipcRenderer.invoke('mateclaw-desktop:workspace-tree', options),
  workspaceGlob: (options) => ipcRenderer.invoke('mateclaw-desktop:workspace-glob', options),
  workspaceGrep: (options) => ipcRenderer.invoke('mateclaw-desktop:workspace-grep', options),
  readFileSnippet: (options) => ipcRenderer.invoke('mateclaw-desktop:read-file-snippet', options),
  writeWorkspacePatch: (options) => ipcRenderer.invoke('mateclaw-desktop:write-workspace-patch', options),
  gitStatus: (options) => ipcRenderer.invoke('mateclaw-desktop:git-status', options),
  gitDiff: (options) => ipcRenderer.invoke('mateclaw-desktop:git-diff', options),
  runReadonlyCommand: (options) => ipcRenderer.invoke('mateclaw-desktop:run-readonly-command', options),
  prepareApprovalCommand: (options) => ipcRenderer.invoke('mateclaw-desktop:prepare-approval-command', options),
  approveCommandRequest: (options) => ipcRenderer.invoke('mateclaw-desktop:approve-command-request', options),
  denyCommandRequest: (options) => ipcRenderer.invoke('mateclaw-desktop:deny-command-request', options),
  executeApprovedCommand: (options) => ipcRenderer.invoke('mateclaw-desktop:execute-approved-command', options),
  ingestHarnessToolResult: (options) => ipcRenderer.invoke('mateclaw-desktop:ingest-harness-tool-result', options),
  writeTextFile: (payload) => ipcRenderer.invoke('mateclaw-desktop:write-text-file', payload),
  revealPath: (targetPath) => ipcRenderer.invoke('mateclaw-desktop:reveal-path', targetPath),
  openPath: (targetPath) => ipcRenderer.invoke('mateclaw-desktop:open-path', targetPath),
  closeCurrentWindow: () => ipcRenderer.invoke('mateclaw-desktop:close-current-window'),
})