CREATE TABLE IF NOT EXISTS mate_wiki_processing_job (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    kb_id               BIGINT       NOT NULL,
    raw_id              BIGINT       NOT NULL,
    job_type            VARCHAR(32)  NOT NULL DEFAULT 'heavy_ingest',
    stage               VARCHAR(64)  NOT NULL DEFAULT 'queued',
    status              VARCHAR(32)  NOT NULL DEFAULT 'queued',
    primary_model_id    BIGINT,
    current_model_id    BIGINT,
    fallback_chain_json TEXT,
    retry_count         INT          NOT NULL DEFAULT 0,
    max_retries         INT          NOT NULL DEFAULT 3,
    error_code          VARCHAR(64),
    error_message       TEXT,
    resume_from_stage   VARCHAR(64),
    meta_json           TEXT,
    started_at          DATETIME(3),
    finished_at         DATETIME(3),
    create_time         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted             TINYINT      NOT NULL DEFAULT 0,
    INDEX idx_wpj_raw    (raw_id),
    INDEX idx_wpj_status (status),
    INDEX idx_wpj_kb     (kb_id, status)
);
