-- Workspace-scoped provider credentials and model defaults.
-- Legacy global tables remain the catalog/default-workspace store.
CREATE TABLE IF NOT EXISTS mate_workspace_model_provider (
    id                              BIGINT       NOT NULL PRIMARY KEY,
    workspace_id                    BIGINT       NOT NULL,
    provider_id                     VARCHAR(64)  NOT NULL,
    name                            VARCHAR(128) NOT NULL,
    api_key_prefix                  VARCHAR(32),
    chat_model                      VARCHAR(64),
    api_key_encrypted               TEXT,
    base_url                        VARCHAR(512),
    generate_kwargs                 TEXT,
    is_custom                       TINYINT(1)   NOT NULL DEFAULT 0,
    is_local                        TINYINT(1)   NOT NULL DEFAULT 0,
    support_model_discovery         TINYINT(1)   NOT NULL DEFAULT 0,
    support_connection_check        TINYINT(1)   NOT NULL DEFAULT 0,
    freeze_url                      TINYINT(1)   NOT NULL DEFAULT 0,
    require_api_key                 TINYINT(1)   NOT NULL DEFAULT 1,
    auth_type                       VARCHAR(16)  NOT NULL DEFAULT 'api_key',
    oauth_access_token_encrypted    TEXT,
    oauth_refresh_token_encrypted   TEXT,
    oauth_expires_at                BIGINT,
    oauth_account_id                VARCHAR(128),
    fallback_priority               INT          NOT NULL DEFAULT 0,
    enabled                         TINYINT(1)   NOT NULL DEFAULT 0,
    create_time                     DATETIME     NOT NULL,
    update_time                     DATETIME     NOT NULL,
    UNIQUE KEY uk_ws_model_provider (workspace_id, provider_id),
    INDEX idx_ws_model_provider_workspace (workspace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mate_workspace_model_config (
    id                       BIGINT       NOT NULL PRIMARY KEY,
    workspace_id             BIGINT       NOT NULL,
    name                     VARCHAR(128) NOT NULL,
    provider                 VARCHAR(64)  NOT NULL,
    model_name               VARCHAR(128) NOT NULL,
    description              TEXT,
    temperature              DOUBLE,
    max_tokens               INT,
    max_input_tokens         INT,
    request_timeout_seconds  INT,
    top_p                    DOUBLE,
    enable_search            TINYINT(1)   NOT NULL DEFAULT 0,
    search_strategy          VARCHAR(32),
    builtin                  TINYINT(1)   NOT NULL DEFAULT 1,
    enabled                  TINYINT(1)   NOT NULL DEFAULT 1,
    is_default               TINYINT(1)   NOT NULL DEFAULT 0,
    model_type               VARCHAR(32)  NOT NULL DEFAULT 'chat',
    modalities               TEXT,
    create_time              DATETIME     NOT NULL,
    update_time              DATETIME     NOT NULL,
    deleted                  INT          NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ws_model_config (workspace_id, provider, model_name),
    INDEX idx_ws_model_config_workspace (workspace_id),
    INDEX idx_ws_model_config_default (workspace_id, is_default, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
